import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Employee Creator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[url('../public/bg-img.jpg')] bg-contain bg-no-repeat bg-center bg-fixed h-screen">
        {children}
      </body>
    </html>
  );
}
